### ISSUE TITLE
Group chat not being initiated

### ISSUE THREAD

**Issue by vipulyaara** [Espreccino/PepperTalkAndroidSDK-Examples#1]
I have read the docs and tried to initiate a group chat.

``` java
PepperTalk.getInstance(getActivity())
                .createGroup("grp:vipulk", "name",
                        imageUrl,
                        groupMembers, new GroupCallback(...);

PepperTalk.getInstance(getActivity())
.joinGroup("grp:vipulk", groupMembers, new GroupCallback(...));

PepperTalk.getInstance(getActivity()).chatWithParticipant("grp:vipulk")
                .start();
```

All the callbacks return success. But it probably tries to initiate a chat with userId "grp:vipulk" rather than creating and posting in a group. (Shows a "SORRY, INVAID USER" screen).
Am I missing something here?

**Comment by jebu** [comment]
@vipulyaara The group name should contain grp: So the right way to do it would be

``` java
PepperTalk.getInstance(getActivity())
                .createGroup("grp:vipulk", "name",
                        imageUrl,
                        groupMembers, new GroupCallback(...);

PepperTalk.getInstance(getActivity())
.joinGroup("grp:vipulk", groupMembers, new GroupCallback(...));

PepperTalk.getInstance(getActivity()).chatWithParticipant("grp:vipulk")
                .start();
```

**Comment by vipulyaara** [comment]
Tried this one too. Same results.
![screenshot_2015-04-16-19-42-16](https://cloud.githubusercontent.com/assets/6247940/7182718/d54ffc5c-e470-11e4-9c57-347c66aca263.png)

**Comment by jebu** [comment]
it says grp:vipul and the group was created as grp:vipulk did you miss out the "k" at the end of the group name?

**Comment by vipulyaara** [comment]
Oh I am sorry. This was older screenshot. My mistake. I didn't miss it. The id is same as group created. See the updated code.

**Comment by jebu** [comment]
could you post a full snippet of what you are doing? I dont see any groups associated with your account so the group creation looks like its not gone through

**Comment by vipulyaara** [comment]
Hey thanks for the support. It worked with some tweak in the code. I should have made all the operations synchronous. My bad. It might have been trying to initiate chat before the group was created. Thanks again for the support.

**Comment by jebu** [comment]
Wonderful.
